In [1]:
import numpy as np

In [5]:
a = np.linspace(0,1,11)

In [7]:
b = np.array(list(range(4)))

In [9]:
a[b]

array([0. , 0.1, 0.2, 0.3])

In [45]:
from scipy.sparse import dia_matrix, eye
n = 10
offsets = np.array([0, -1, 1, n-1, 1-n])
data = np.array([-2*np.ones(n), 0*np.ones(n), 0*np.ones(n), 0*np.ones(n), 0*np.ones(n)])
Dxx = dia_matrix((data, offsets), shape=(n,n))

In [42]:
x = np.random.randn(10)

In [47]:
(eye(10) - Dxx).toarray()

array([[3., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 3., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 3., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 3., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 3., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 3., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 3.]])

In [43]:
Dxx.dot(x)

array([-1.03768077, -3.26564466, -0.29702764,  0.70726998, -0.09628959,
        0.54978103,  0.62895275,  3.09208259,  0.5178807 , -6.50305789])

In [33]:
from scipy.sparse.linalg import inv

In [36]:
inv(Dxx).toarray()

array([[-1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15],
       [-1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15],
       [-1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15],
       [-1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15],
       [-1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.44758559e+15, -1.44758559e+15, -1.44758559e+15,
        -1.

In [50]:
b = np.arange(0,100,10)

In [49]:
a = np.random.randn(100,100)

In [52]:
a[0,b].reshape(-1,1)

array([[-0.02627898],
       [-2.24575309],
       [ 0.09381083],
       [-0.18640083],
       [-0.16260481],
       [-0.30969395],
       [-0.32758321],
       [ 1.5967689 ],
       [-0.50463366],
       [-0.69116916]])